#!groovy

/*
The MIT License
Copyright (c) 2015-, CloudBees, Inc., and a number of other of contributors
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.
        THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

pipeline {
    agent { node { label 'linux' } }
    environment {
        WORKSPACE=pwd()
        HOME="/var/jenkins_home"
        PATH="/opt/usr/bin:$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
        JOB_NAME="kontact-appimage"
    }
    options {
        disableConcurrentBuilds()
        timestamps()
    }
    triggers { pollSCM('H */4 * * 1-5')
                    upstream(upstreamProjects: 'qt5-artifact,kde-common-deps-artifact,kde-kf5-artifact', threshold: hudson.model.Result.SUCCESS)
   }
    stages {
            stage( 'Checkout' ) {
                steps {
                    checkout changelog: true, poll: false, scm: [$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, \
                    extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: '.']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://anongit.kde.org/appimage-packaging']]]
                    checkout changelog: true, poll: false, scm: [$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, \
                    extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: "$JOB_NAME/appimage-template"]], submoduleCfg: [], userRemoteConfigs: [[url: 'https://anongit.kde.org/sysadmin/appimage-tooling']]]
                    copyArtifacts projectName: "kde-kf5-artifact", selector: lastCompleted(), target: "${env.WORKSPACE}/${env.JOB_NAME}", flatten: true
                    sh "pwd && ls -l"
                }
            }
            stage( 'Setup' ) {
                steps {
                    sh 'echo "gem: --no-rdoc --no-ri" >> $HOME/.gemrc'
                    sh '''#!/usr/bin/env bash
                        set -e
                        export PATH=$PATH:$HOME/.rbenv/bin
                        if [[ ! -d ~/.rbenv ]] ; then
                        git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
                        git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
                        if [[ ! -d $HOME/.rbenv/versions/2.4.1 ]] ; then
                            rbenv install 2.4.1
                        fi
                        eval "$(rbenv init -)"
                        rbenv local 2.4.1 && gem install bundler && ls -l && bundle install --binstubs && bundle show rspec
                        else
                        echo "Rbenv exists, moving on"
                        if [[ ! -d $HOME/.rbenv/versions/2.4.1 ]] ; then
                            rbenv install 2.4.1
                        fi
                        eval "$(rbenv init -)"
                        rbenv local 2.4.1 && gem install bundler && ls -l && bundle install --binstubs && bundle show rspec
                        cd $JOB_NAME && bundle install
                        fi

                        '''
                    }
            }
            stage( 'Build' ) {
                steps {
                    sh "cd $JOB_NAME"
                    sh '''#!/usr/bin/env bash
                        set -e
                        cd $JOB_NAME
                        export PATH=$PATH:$HOME/.rbenv/bin
                        eval "$(rbenv init -)"
                        rbenv local 2.4.1
                        bundle exec deploy.rb
                        '''
                    }
            }
            stage('Tests') {
                steps {
                step([$class: 'LogParserPublisher', failBuildOnError: true, projectRulePath: "$JOB_NAME/appimage-template/parser.rules", showGraphs: true, unstableOnWarning: true, useProjectRule: true])
            }
        }
    }
}
